### ISSUE TITLE
its only working for 1.0.X ?

### ISSUE THREAD

**Issue by ghost** [Dnawrkshp/ty-1-tools#2]
Could you update it for the newer one pls  👍 

is a mod menu for ingame possible?

the speed/jump worked
want a teleport one :< 
so i can practice for runs

ty for your previous work. 💯

**Comment by Dnawrkshp** [comment]
Mod manager has been updated for ty1 r4704_v1.44.

Closing the issue. If you still want a teleport mod please open a new issue and describe what you want in more detail. Thanks
